name: WolfTPM CMake Build Tests

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#pull wolfTPM
    - uses: actions/checkout@master

# Install cmake
    - name: Install cmake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

#pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl
    - name: Build wolfssl
      working-directory: ./wolfssl
      run: |
        mkdir build
        cd build
        # wolfSSL PR 7188 broke "make install" unless WOLFSSL_INSTALL is set
        cmake -DWOLFSSL_TPM=yes -DWOLFSSL_INSTALL=yes -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install" ..
        cmake --build .
        cmake --install .

#build wolftpm
    - name: Build wolfTPM
      run: |
        mkdir build
        cd build
        cmake -DWOLFTPM_INTERFACE=SWTPM -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install" -DWITH_WOLFSSL="$GITHUB_WORKSPACE/install" ..
        cmake --build .
        cmake --install .
